In [10]:
import torch
import numpy as np

In [26]:
list1 = [[1,2],[3,4],[5,6]]
t3 = torch.as_tensor(list1)
t3

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [29]:
t3.size()

torch.Size([3, 2])

In [13]:
arr1 = np.array([[1,2],[3,4]])
t4 = torch.from_numpy(arr1)
t4

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [33]:
torch.empty(3,4)
#초기화 하지 않은 값.

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
torch.randn(10)

tensor([-1.0373, -0.2074,  1.6153, -0.1095,  1.5123,  2.1355,  0.2549, -0.5827,
        -1.2990,  0.1081])

In [34]:
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [35]:
torch.logspace(0,10,5)

tensor([1.0000e+00, 3.1623e+02, 1.0000e+05, 3.1623e+07, 1.0000e+10])

In [36]:
t2 = torch.arange(6)

In [37]:
t2

tensor([0, 1, 2, 3, 4, 5])

In [38]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [40]:
torch.randint(5,size=(2,2,)).dtype

torch.int64

In [45]:
torch.ones((2,2,)).dtype

torch.float32

In [46]:
t2.view((1,2,3))

tensor([[[0, 1, 2],
         [3, 4, 5]]])

In [47]:
t2.view((3,1,2))

tensor([[[0, 1]],

        [[2, 3]],

        [[4, 5]]])

In [48]:
t2.view((3,1,2)).squeeze()

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [49]:
t2.view((3,1,2)).squeeze().unsqueeze(2)

tensor([[[0],
         [1]],

        [[2],
         [3]],

        [[4],
         [5]]])

In [51]:
t2.view((3,1,2)).squeeze().unsqueeze(2).shape

torch.Size([3, 2, 1])

In [52]:
t2.view((3,1,2)).squeeze().unsqueeze(2).size()

torch.Size([3, 2, 1])

In [60]:
x = torch.rand(2,2,requires_grad=True)

In [61]:
print(x)

tensor([[0.6739, 0.2130],
        [0.6513, 0.3468]], requires_grad=True)


In [62]:
y = torch.sum(x*3)
print(y)

tensor(5.6552, grad_fn=<SumBackward0>)


In [63]:
y.backward()

In [64]:
x.grad

tensor([[3., 3.],
        [3., 3.]])

In [65]:
from torch.autograd import grad

In [66]:
x1 = torch.tensor(2,requires_grad=True, dtype=torch.float32)
x2 = torch.tensor(3,requires_grad=True, dtype=torch.float32)
x3 = torch.tensor(1,requires_grad=True, dtype=torch.float32)
x4 = torch.tensor(4,requires_grad=True, dtype=torch.float32)

In [67]:
z1 = x1 * x2
z2 = x3 * x4
f = z1 + z2

In [68]:
f.backward()

In [69]:
print(f'radient of x1 = {x1.grad}')
print(f'radient of x2 = {x2.grad}')
print(f'radient of x3 = {x3.grad}')
print(f'radient of x4 = {x4.grad}')

radient of x1 = 3.0
radient of x2 = 2.0
radient of x3 = 4.0
radient of x4 = 1.0


In [84]:
a0 = torch.tensor(2,requires_grad=True, dtype=torch.float32)
a1 = torch.tensor(2,requires_grad=True, dtype=torch.float32)
a2 = torch.tensor(3,requires_grad=True, dtype=torch.float32)

In [85]:
b1 = a0*a1*a2

In [86]:
print(b1)

tensor(12., grad_fn=<MulBackward0>)


In [87]:
b1.backward()

In [88]:
print(b1)

tensor(12., grad_fn=<MulBackward0>)


In [89]:
a1.grad 

tensor(6.)

In [90]:
a2.grad

tensor(4.)

In [91]:
b1.data

tensor(12.)

In [95]:
x = torch.tensor(1.0,requires_grad=True)
y= x*2
y.requires_grad

True

In [96]:
x = torch.tensor(1.0,requires_grad=True)
with torch.no_grad():
    y= x*2
y.requires_grad

False